/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuleD;

/**
 *
 * @author Alex Ng
 */
public class ModuleDDriver extends javax.swing.JFrame {

    /**
     * Creates new form ModuleDDriver
     */
    public ModuleDDriver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTimeClock = new javax.swing.JButton();
        btnCompleteJob = new javax.swing.JButton();
        btnTrackOrder = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTimeClock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTimeClock.setText("Time Clock");
        btnTimeClock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimeClockMouseClicked(evt);
            }
        });

        btnCompleteJob.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCompleteJob.setText("Complete Job");
        btnCompleteJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCompleteJobMouseClicked(evt);
            }
        });

        btnTrackOrder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTrackOrder.setText("Track Order");
        btnTrackOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrackOrderMouseClicked(evt);
            }
        });

        btnSchedule.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSchedule.setText("Schedule");
        btnSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScheduleMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuleD/calendar_icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimeClock, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompleteJob, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrackOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnTimeClock, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnCompleteJob, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTrackOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrackOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrackOrderMouseClicked
        this.dispose();
        TrackOrder driver = new TrackOrder();
        driver.setLocationRelativeTo(null);
        driver.setDefaultCloseOperation(EXIT_ON_CLOSE);
        driver.setVisible(true);
    }//GEN-LAST:event_btnTrackOrderMouseClicked

    private void btnScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScheduleMouseClicked
        this.dispose();
        CreateJob driver = new CreateJob();
        driver.setLocationRelativeTo(null);
        driver.setDefaultCloseOperation(EXIT_ON_CLOSE);
        driver.setVisible(true); 
    }//GEN-LAST:event_btnScheduleMouseClicked

    private void btnCompleteJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteJobMouseClicked
        this.dispose();
        DeleteCompleteJob driver = new DeleteCompleteJob();
        driver.setLocationRelativeTo(null);
        driver.setDefaultCloseOperation(EXIT_ON_CLOSE);
        driver.setVisible(true);
    }//GEN-LAST:event_btnCompleteJobMouseClicked

    private void btnTimeClockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimeClockMouseClicked
        this.dispose();
        ClockIn clockIn = new ClockIn();
        clockIn.setLocationRelativeTo(null);
        clockIn.setDefaultCloseOperation(EXIT_ON_CLOSE);
        clockIn.setVisible(true);
    }//GEN-LAST:event_btnTimeClockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuleDDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuleDDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuleDDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuleDDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuleDDriver driver = new ModuleDDriver();
                driver.setLocationRelativeTo(null);
                driver.setDefaultCloseOperation(EXIT_ON_CLOSE);
                driver.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompleteJob;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JButton btnTimeClock;
    private javax.swing.JButton btnTrackOrder;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
